# Generated by Django 5.0.6 on 2024-06-12 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
