# Generated by Django 5.0.6 on 2024-06-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0002_alter_recording_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='title',
        ),
        migrations.AlterField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
