# Generated by Django 5.0.6 on 2024-06-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0003_remove_recording_title_alter_recording_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(upload_to='recordings/'),
        ),
    ]
