# Generated by Django 5.0.6 on 2024-06-13 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0004_recording_title_alter_recording_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription_text', models.TextField()),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioapp.recording')),
            ],
        ),
    ]
